### ISSUE TITLE
Modal not displayed, this.setState is not a function

### ISSUE THREAD

**Issue by phun-ky** [reactjs/react-modal#386]
Getting this error in 1.7.7. Modal works fine in 1.6.1. What could be the issue?

**Comment by diasbruno** [comment]
Hey @phun-ky. Can you provide more information for this issue?

**Comment by diasbruno** [comment]
This seems related to #325.
